import {test, expect, Locator} from '@playwright/test';

test('autocomplete dropdown', async ({page}) => {
    await page.goto('https://www.flipkart.com/');

    const searchInput: Locator = page.getByRole('textbox', { name: /search/i });
    
    //Handle modal pop-up
    const modalCloseButton: Locator = page.getByRole('button', { name: '✕' });
    await expect(modalCloseButton).toBeVisible();
    await modalCloseButton.click();
    await expect(searchInput).toBeVisible();
    await searchInput.fill('smart');

    //The search box in this page is a autocomplete searchbox, the autogenerated results will disappear when we click outside the box
    //To interact with these elements in the browser DOM we use Cntl+Shift+P to open the command palette and search for Emulate a focused page 

    //This will capture all the autosuggested results
    //const autocompleteContainer: Locator = page.locator('ul[class="VCplLH lTpUwR bRjjIF _1psv1ze5l _1psv1ze9l _1psv1ze7c _1cisqlf2"]');
    //await expect(autocompleteContainer).toBeVisible();
    const autocompleteResults: Locator = page.locator('ul>li');
    await expect(autocompleteResults.nth(0)).toBeVisible();

    //Then we count how many suggested options are returned
    const optionsCount = await autocompleteResults.count();
    console.log('Number of autocomplete options: ' + optionsCount);

    console.log('The autocomplete options are:');
    for(let i=0; i<optionsCount; i++){
        console.log('Option: ' + await autocompleteResults.nth(i).innerText() + '\n' + await autocompleteResults.nth(i).textContent() + '\n\n');
    }

    //select and click on the smartphone option
    for(let i=0; i<optionsCount; i++){
        const optionText = await autocompleteResults.nth(i).innerText();
        if(optionText.toLowerCase().includes('smartphone')){
            await autocompleteResults.nth(i).click();
            break;
        }
    }

    await page.waitForTimeout(5000);
});